### ISSUE TITLE
[프로젝트 요구사항] 1. 시계열 차트 만들기

### ISSUE THREAD

**Issue by Chaam2** [Chaam2/data-visualization#1]
### Assignment
- [x]  주어진 JSON 데이터의 `key`값(시간)을 기반으로 시계열 차트를 만들어주세요
- [x]  하나의 차트안에 Area 형태의 그래프와 Bar 형태의 그래프가 모두 존재하는 복합 그래프로 만들어주세요
- [x]  Area 그래프의 기준값은 `value_area` 값을 이용해주세요
- [x]  Bar 그래프의 기준값은 `value_bar` 값을 이용해주세요
- [x]  차트의 Y축에 대략적인 수치를 표현해주세요(예시 이미지 참고)
![image](https://github.com/Chaam2/data-visualization/assets/126763111/619f578c-b359-4250-9433-5bec039eb744)
---
### Todo
- [x] 차트 라이브러리 비교 및 선택
- [x] mock-data 호출 및 데이터 관리 로직 구현

**Comment by Chaam2** [comment]
- 차트 라이브러리
[recharts](https://www.npmjs.com/package/recharts)와 [react-chartjs-2](https://www.npmjs.com/package/react-chartjs-2)중 비교적 더 리액트에 특화된것으로 보이는 recharts라이브러리로 구현해보기로 함
(+ recharts가 더 최근까지 업데이트 되었고 주간 다운로드 수가 훨씬 더 많았다)

**Comment by Chaam2** [comment]
<img width="1211" alt="image" src="https://github.com/Chaam2/data-visualization/assets/126763111/79ff3292-6a72-4854-9a5e-4bc419e23fc8">

- rechart라이브러리로 데이터 기반  기본적인 차트 구현
