### ISSUE TITLE
[프로젝트 요구사항] 2. 필터링 기능 구현

### ISSUE THREAD

**Issue by Chaam2** [Chaam2/data-visualization#3]
### Assignment
- [x] 필터링 기능을 구현해주세요, 필터링은 특정 데이터 구역을 하이라이트 하는 방식으로 구현해주세요
- [x] 필터링 기능은 버튼 형태로 ID값(지역이름)을 이용해주세요
- [x] 필터링 시 버튼에서 선택한 ID값과 동일한 ID값을 가진 데이터 구역만 하이라이트 처리를 해주세요
- [x] 특정 데이터 구역을 클릭 시에도 필터링 기능과 동일한 형태로 동일한 ID값을 가진 데이터 구역을 하이라이트해주세요
> **예시**

| 필터링 X | 필터링 O |
| :---: | :---: |
|   ![image](https://github.com/Chaam2/data-visualization/assets/126763111/08154c6d-7b93-49c3-98fb-16463cf630d3) | ![image](https://github.com/Chaam2/data-visualization/assets/126763111/e7e96ad7-c08d-4b85-8d3f-7c1a087f449e)  |

---
### Todo
- [ ]

**Comment by Chaam2** [comment]
### useSearchParams
1.  get()메서드를 이용해 searchParams안에 있는 데이터를 가져올 수 있다. 
  ```js
    const [searchParams, setSearchParams] = useSearchParams();

    const id = searchParams.get('id');
```

2. setSearchParams 
```js
<button onClick={() => setSearchParams({ id: "123" })}></button>
```
setSearchParams의 인자로 변경할 데이터의 객체를 넣어주면 버튼을 클릭했을때 데이터 경로의 데이터가 변화하게 된다.

---
-> useSearchParams를 활용해 차트 클릭 시 url을 선택된 차트의 id로 변경하고, url param값에 따라 css스타일링(하이라이트)을 주는 방식으로 구현

**Comment by Chaam2** [comment]
### JavaScript new Set()활용
- **중복되지 않는 value값 만**을 저장하는 유사객체를 리턴한다.
- `Array.from(set)` 메서드 또는 `[...set]` 스프레드 형식을 통해 array형태로 변환할 수 있다.

참고
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
https://velog.io/@minew1995/JavaScript-new-Set

**Comment by Chaam2** [comment]
<img width="1214" alt="image" src="https://github.com/Chaam2/data-visualization/assets/126763111/c3bd0e22-e4d8-4288-8fed-709ebc6f6184">
